# **Exercise: Basics of Python and Numpy**

### 1. Import numpy and print the numpy version. (Hint: use ```__version___``` attribute to check package version.)

In [1]:
import numpy as np
np.__version__

'1.24.4'

### 2. Create a 4 x 5 matrix filled with random values. Name it as ```x```.

In [2]:
x = np.random.random((4,5))
x

array([[0.17985626, 0.59134216, 0.92522453, 0.36133283, 0.52599187],
       [0.78968312, 0.1312004 , 0.95191042, 0.37330208, 0.02785262],
       [0.2567145 , 0.47553512, 0.00982234, 0.14815523, 0.41484381],
       [0.71174702, 0.66461294, 0.17706759, 0.32388419, 0.7034516 ]])

### 3. Create a 3 x 3 matrix filled with [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Name it as ```y```.

In [3]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 4. Swap the first two rows of ```x```.

In [4]:
x[[0,1],:] = x[[1,0],:]
x

array([[0.78968312, 0.1312004 , 0.95191042, 0.37330208, 0.02785262],
       [0.17985626, 0.59134216, 0.92522453, 0.36133283, 0.52599187],
       [0.2567145 , 0.47553512, 0.00982234, 0.14815523, 0.41484381],
       [0.71174702, 0.66461294, 0.17706759, 0.32388419, 0.7034516 ]])

### 5. Create a random numpy array with shape (100, 2) and name it ```z```. Each row indicates the coordinates of a point. Compute point by point distances.

In [5]:
z = np.random.random((100,2))
zx, zy = np.atleast_2d(z[:, 0], z[:, 1])
d = np.sqrt((zx - zx.T)**2 + (zy - zy.T)**2)
d

array([[0.        , 0.20592725, 0.49729764, ..., 0.2816772 , 0.11438527,
        0.61240118],
       [0.20592725, 0.        , 0.31089246, ..., 0.45110297, 0.22433048,
        0.41218004],
       [0.49729764, 0.31089246, 0.        , ..., 0.66808795, 0.53515613,
        0.31274939],
       ...,
       [0.2816772 , 0.45110297, 0.66808795, ..., 0.        , 0.37795912,
        0.86015811],
       [0.11438527, 0.22433048, 0.53515613, ..., 0.37795912, 0.        ,
        0.5885272 ],
       [0.61240118, 0.41218004, 0.31274939, ..., 0.86015811, 0.5885272 ,
        0.        ]])

### 6. Subtract the mean of each row of ```y```.

In [6]:
y_ = np.mean(y, axis=1, keepdims=True)
y_

array([[2.],
       [5.],
       [8.]])

In [7]:
y - y_

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

### 7. Add a vector [1, 0, 1] to each row of ```y``` using broadcasting and name the resulting numpy array as ```yy```.

In [8]:
yy = y + np.array([1,0,1])
yy

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

### 8. For each row in ```yy```, extract the value that are not equal to the other two values. Organize these values as a numpy array.

In [9]:
yy_neq = []
row, col = yy.shape
for i in range(row):
    for j in range(col):
        yy_neq_row = []
        if yy[i][j] != yy[i][(j+1)%col] and yy[i][j] != yy[i][(j+2)%col]: 
            #print(yy[i][j])
            yy_neq_row.append(yy[i][j])
    yy_neq.append(yy_neq_row)

In [10]:
np.array(yy_neq)

array([[ 4],
       [ 7],
       [10]])